//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC3_HERRAMIENTAS_DE_PROGRAMAMCION
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        public int ID { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Nombres { get; set; }
        public int Edad { get; set; }
    }
}
